# CHANGE-TO-YOURNAME-aws-node-http-api-project
service: ws-aws-node-http-api-project #name of the service
frameworkVersion: '3' #just the version of the framework

provider: #configuration for the cloud provider
  name: aws
  runtime: nodejs18.x #runtime for the function we will use
  region: ap-southeast-1 #region where we will deploy our service in aws

functions:
  api: #name of the lambda function
    handler: index.handler #name of the file and the name of the function
    events: #events that will trigger the function
      - httpApi: #type of event
          path: / #path of the event
          method: get #method of the event

plugins: #plugins that we will use
  - serverless-offline #plugin to run the service locally