name: CICD for Serverless Application
run-name: ${{ github.actor }} is doing CICD for Serverless Application

on:
  push:
    branches: [ main, "*" ]

jobs:
  pre-deploy: #job name(can be any name,which will appear on the github action page/pipeline)
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggerd by a ${{ github.event_name }} event."

  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Run installation of dependencies command
        run: npm install